{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "14404551-16c0-4639-a668-ac64beb074df",
   "metadata": {},
   "outputs": [],
   "source": [
    "from abc import ABC, abstractmethod\n",
    "import csv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dfaa0c20-60e0-4b55-ac2c-04069cb41c4a",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Person(ABC):\n",
    "\n",
    "    @abstractmethod\n",
    "    def display(self):\n",
    "        pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2f106ea0-6021-417e-a873-c1a73559b059",
   "metadata": {},
   "outputs": [],
   "source": [
    "class BankAccount(Person):\n",
    "\n",
    "    def __init__(self, account_no, name, balance=0):\n",
    "\n",
    "        self.__account_no = account_no\n",
    "        self.__name = name\n",
    "        self.__balance = balance\n",
    "        self.__history = []\n",
    "\n",
    "    # Getters\n",
    "    def get_account(self):\n",
    "        return self.__account_no\n",
    "\n",
    "    def get_name(self):\n",
    "        return self.__name\n",
    "\n",
    "    def get_balance(self):\n",
    "        return self.__balance\n",
    "\n",
    "    def get_history(self):\n",
    "        return self.__history\n",
    "\n",
    "    # Deposit\n",
    "    def deposit(self, amount):\n",
    "\n",
    "        self.__balance += amount\n",
    "        self.__history.append(\"Deposited ₹\" + str(amount))\n",
    "\n",
    "    # Withdraw\n",
    "    def withdraw(self, amount):\n",
    "\n",
    "        if amount <= self.__balance:\n",
    "\n",
    "            self.__balance -= amount\n",
    "            self.__history.append(\"Withdraw ₹\" + str(amount))\n",
    "\n",
    "        else:\n",
    "            print(\"Insufficient Balance\")\n",
    "\n",
    "    # Display\n",
    "    def display(self):\n",
    "\n",
    "        print(\"Account No :\", self.__account_no)\n",
    "        print(\"Name       :\", self.__name)\n",
    "        print(\"Balance    :\", self.__balance)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7d49eb3d-682a-48aa-9b95-4353eb68c63a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Account No : 1001\n",
      "Name       : Parth\n",
      "Balance    : 5000\n"
     ]
    }
   ],
   "source": [
    "account = BankAccount(\"1001\", \"Parth\", 5000)\n",
    "\n",
    "account.display()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a3c1c02a-0195-44c3-a773-64c2c6978fe8",
   "metadata": {},
   "outputs": [],
   "source": [
    "class BankManagement:\n",
    "\n",
    "    def __init__(self):\n",
    "        self.accounts = []\n",
    "\n",
    "    # Create Account\n",
    "    def create_account(self):\n",
    "\n",
    "        try:\n",
    "\n",
    "            account_no = input(\"Enter Account Number: \")\n",
    "            name = input(\"Enter Account Holder Name: \")\n",
    "            balance = float(input(\"Enter Opening Balance: \"))\n",
    "\n",
    "            account = BankAccount(account_no, name, balance)\n",
    "\n",
    "            self.accounts.append(account)\n",
    "\n",
    "            print(\"Account Created Successfully!\")\n",
    "\n",
    "        except ValueError:\n",
    "            print(\"Invalid Amount!\")\n",
    "\n",
    "    # Display Accounts\n",
    "    def display_accounts(self):\n",
    "\n",
    "        if len(self.accounts) == 0:\n",
    "            print(\"No Accounts Found\")\n",
    "            return\n",
    "\n",
    "        print(\"\\nAccount Details\\n\")\n",
    "\n",
    "        for account in self.accounts:\n",
    "            account.display()\n",
    "            print(\"----------------------\")\n",
    "\n",
    "    # Search Account\n",
    "    def search_account(self):\n",
    "\n",
    "        account_no = input(\"Enter Account Number: \")\n",
    "\n",
    "        for account in self.accounts:\n",
    "\n",
    "            if account.get_account() == account_no:\n",
    "                print(\"\\nAccount Found\\n\")\n",
    "                account.display()\n",
    "                return\n",
    "\n",
    "        print(\"Account Not Found\")\n",
    "\n",
    "    # Deposit\n",
    "    def deposit_money(self):\n",
    "\n",
    "        account_no = input(\"Enter Account Number: \")\n",
    "\n",
    "        for account in self.accounts:\n",
    "\n",
    "            if account.get_account() == account_no:\n",
    "\n",
    "                amount = float(input(\"Enter Amount: \"))\n",
    "\n",
    "                account.deposit(amount)\n",
    "\n",
    "                print(\"Amount Deposited Successfully!\")\n",
    "                return\n",
    "\n",
    "        print(\"Account Not Found\")\n",
    "\n",
    "    # Withdraw\n",
    "    def withdraw_money(self):\n",
    "\n",
    "        account_no = input(\"Enter Account Number: \")\n",
    "\n",
    "        for account in self.accounts:\n",
    "\n",
    "            if account.get_account() == account_no:\n",
    "\n",
    "                amount = float(input(\"Enter Amount: \"))\n",
    "\n",
    "                account.withdraw(amount)\n",
    "\n",
    "                return\n",
    "\n",
    "        print(\"Account Not Found\")\n",
    "\n",
    "    # Balance\n",
    "    def check_balance(self):\n",
    "\n",
    "        account_no = input(\"Enter Account Number: \")\n",
    "\n",
    "        for account in self.accounts:\n",
    "\n",
    "            if account.get_account() == account_no:\n",
    "\n",
    "                print(\"Current Balance = ₹\", account.get_balance())\n",
    "\n",
    "                return\n",
    "\n",
    "        print(\"Account Not Found\")\n",
    "\n",
    "    # Transaction History\n",
    "    def transaction_history(self):\n",
    "\n",
    "        account_no = input(\"Enter Account Number: \")\n",
    "\n",
    "        for account in self.accounts:\n",
    "\n",
    "            if account.get_account() == account_no:\n",
    "\n",
    "                print(\"\\nTransaction History\")\n",
    "\n",
    "                history = account.get_history()\n",
    "\n",
    "                if len(history) == 0:\n",
    "                    print(\"No Transactions\")\n",
    "\n",
    "                else:\n",
    "                    for item in history:\n",
    "                        print(item)\n",
    "\n",
    "                return\n",
    "\n",
    "        print(\"Account Not Found\")\n",
    "\n",
    "    # Save File\n",
    "    def save_file(self):\n",
    "\n",
    "        file = open(\"accounts.csv\", \"w\", newline=\"\")\n",
    "\n",
    "        writer = csv.writer(file)\n",
    "\n",
    "        for account in self.accounts:\n",
    "\n",
    "            history = \"|\".join(account.get_history())\n",
    "\n",
    "            writer.writerow([\n",
    "                account.get_account(),\n",
    "                account.get_name(),\n",
    "                account.get_balance(),\n",
    "                history\n",
    "            ])\n",
    "\n",
    "        file.close()\n",
    "\n",
    "        print(\"Data Saved Successfully!\")\n",
    "\n",
    "    # Load File\n",
    "    def load_file(self):\n",
    "\n",
    "        try:\n",
    "\n",
    "            file = open(\"accounts.csv\", \"r\")\n",
    "\n",
    "            reader = csv.reader(file)\n",
    "\n",
    "            self.accounts = []\n",
    "\n",
    "            for row in reader:\n",
    "\n",
    "                account = BankAccount(\n",
    "                    row[0],\n",
    "                    row[1],\n",
    "                    float(row[2])\n",
    "                )\n",
    "\n",
    "                if row[3]:\n",
    "                    account.get_history().extend(row[3].split(\"|\"))\n",
    "\n",
    "                self.accounts.append(account)\n",
    "\n",
    "            file.close()\n",
    "\n",
    "        except FileNotFoundError:\n",
    "            pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "fcfc073d-713e-48b1-9692-020740e7b25a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "===== Bank Management System =====\n",
      "1. Create Account\n",
      "2. Display Accounts\n",
      "3. Search Account\n",
      "4. Deposit\n",
      "5. Withdraw\n",
      "6. Check Balance\n",
      "7. Transaction History\n",
      "8. Save Data\n",
      "9. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Choice:  1\n",
      "Enter Account Number:  01\n",
      "Enter Account Holder Name:  Parth \n",
      "Enter Opening Balance:  5000\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Account Created Successfully!\n",
      "\n",
      "===== Bank Management System =====\n",
      "1. Create Account\n",
      "2. Display Accounts\n",
      "3. Search Account\n",
      "4. Deposit\n",
      "5. Withdraw\n",
      "6. Check Balance\n",
      "7. Transaction History\n",
      "8. Save Data\n",
      "9. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Choice:  2\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Account Details\n",
      "\n",
      "Account No : 01\n",
      "Name       : Parth \n",
      "Balance    : 5000.0\n",
      "----------------------\n",
      "\n",
      "===== Bank Management System =====\n",
      "1. Create Account\n",
      "2. Display Accounts\n",
      "3. Search Account\n",
      "4. Deposit\n",
      "5. Withdraw\n",
      "6. Check Balance\n",
      "7. Transaction History\n",
      "8. Save Data\n",
      "9. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Choice:  4\n",
      "Enter Account Number:  01\n",
      "Enter Amount:  6000\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Amount Deposited Successfully!\n",
      "\n",
      "===== Bank Management System =====\n",
      "1. Create Account\n",
      "2. Display Accounts\n",
      "3. Search Account\n",
      "4. Deposit\n",
      "5. Withdraw\n",
      "6. Check Balance\n",
      "7. Transaction History\n",
      "8. Save Data\n",
      "9. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Choice:  5\n",
      "Enter Account Number:  01\n",
      "Enter Amount:  50\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "===== Bank Management System =====\n",
      "1. Create Account\n",
      "2. Display Accounts\n",
      "3. Search Account\n",
      "4. Deposit\n",
      "5. Withdraw\n",
      "6. Check Balance\n",
      "7. Transaction History\n",
      "8. Save Data\n",
      "9. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Choice:  6\n",
      "Enter Account Number:  01\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Balance = ₹ 10950.0\n",
      "\n",
      "===== Bank Management System =====\n",
      "1. Create Account\n",
      "2. Display Accounts\n",
      "3. Search Account\n",
      "4. Deposit\n",
      "5. Withdraw\n",
      "6. Check Balance\n",
      "7. Transaction History\n",
      "8. Save Data\n",
      "9. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Choice:  9\n"
     ]
    },
    {
     "ename": "UnicodeEncodeError",
     "evalue": "'charmap' codec can't encode character '\\u20b9' in position 28: character maps to <undefined>",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mUnicodeEncodeError\u001b[39m                        Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[6]\u001b[39m\u001b[32m, line 45\u001b[39m\n\u001b[32m     41\u001b[39m     \u001b[38;5;28;01melif\u001b[39;00m choice == \u001b[33m\"8\"\u001b[39m:\n\u001b[32m     42\u001b[39m         bank.save_file()\n\u001b[32m     43\u001b[39m \n\u001b[32m     44\u001b[39m     \u001b[38;5;28;01melif\u001b[39;00m choice == \u001b[33m\"9\"\u001b[39m:\n\u001b[32m---> \u001b[39m\u001b[32m45\u001b[39m         bank.save_file()\n\u001b[32m     46\u001b[39m         print(\u001b[33m\"Thank You!\"\u001b[39m)\n\u001b[32m     47\u001b[39m         \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[32m     48\u001b[39m \n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[5]\u001b[39m\u001b[32m, line 136\u001b[39m, in \u001b[36mBankManagement.save_file\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    132\u001b[39m         \u001b[38;5;28;01mfor\u001b[39;00m account \u001b[38;5;28;01min\u001b[39;00m self.accounts:\n\u001b[32m    133\u001b[39m \n\u001b[32m    134\u001b[39m             history = \u001b[33m\"|\"\u001b[39m.join(account.get_history())\n\u001b[32m    135\u001b[39m \n\u001b[32m--> \u001b[39m\u001b[32m136\u001b[39m             writer.writerow([\n\u001b[32m    137\u001b[39m                 account.get_account(),\n\u001b[32m    138\u001b[39m                 account.get_name(),\n\u001b[32m    139\u001b[39m                 account.get_balance(),\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\encodings\\cp1252.py:19\u001b[39m, in \u001b[36mIncrementalEncoder.encode\u001b[39m\u001b[34m(self, input, final)\u001b[39m\n\u001b[32m     18\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mencode\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;28minput\u001b[39m, final=\u001b[38;5;28;01mFalse\u001b[39;00m):\n\u001b[32m---> \u001b[39m\u001b[32m19\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[30;43mcodecs\u001b[39;49m\u001b[30;43m.\u001b[39;49m\u001b[30;43mcharmap_encode\u001b[39;49m\u001b[30;43m(\u001b[39;49m\u001b[30;43minput\u001b[39;49m\u001b[30;43m,\u001b[39;49m\u001b[30;43mself\u001b[39;49m\u001b[30;43m.\u001b[39;49m\u001b[30;43merrors\u001b[39;49m\u001b[30;43m,\u001b[39;49m\u001b[30;43mencoding_table\u001b[39;49m\u001b[30;43m)\u001b[39;49m[\u001b[32m0\u001b[39m]\n",
      "\u001b[31mUnicodeEncodeError\u001b[39m: 'charmap' codec can't encode character '\\u20b9' in position 28: character maps to <undefined>"
     ]
    }
   ],
   "source": [
    "bank = BankManagement()\n",
    "\n",
    "bank.load_file()\n",
    "\n",
    "while True:\n",
    "\n",
    "    print(\"\\n===== Bank Management System =====\")\n",
    "    print(\"1. Create Account\")\n",
    "    print(\"2. Display Accounts\")\n",
    "    print(\"3. Search Account\")\n",
    "    print(\"4. Deposit\")\n",
    "    print(\"5. Withdraw\")\n",
    "    print(\"6. Check Balance\")\n",
    "    print(\"7. Transaction History\")\n",
    "    print(\"8. Save Data\")\n",
    "    print(\"9. Exit\")\n",
    "\n",
    "    choice = input(\"Enter Choice: \")\n",
    "\n",
    "    if choice == \"1\":\n",
    "        bank.create_account()\n",
    "\n",
    "    elif choice == \"2\":\n",
    "        bank.display_accounts()\n",
    "\n",
    "    elif choice == \"3\":\n",
    "        bank.search_account()\n",
    "\n",
    "    elif choice == \"4\":\n",
    "        bank.deposit_money()\n",
    "\n",
    "    elif choice == \"5\":\n",
    "        bank.withdraw_money()\n",
    "\n",
    "    elif choice == \"6\":\n",
    "        bank.check_balance()\n",
    "\n",
    "    elif choice == \"7\":\n",
    "        bank.transaction_history()\n",
    "\n",
    "    elif choice == \"8\":\n",
    "        bank.save_file()\n",
    "\n",
    "    elif choice == \"9\":\n",
    "        bank.save_file()\n",
    "        print(\"Thank You!\")\n",
    "        break\n",
    "\n",
    "    else:\n",
    "        print(\"Invalid Choice\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab14f396-4574-46a4-a866-23c2a3c1a492",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
